# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_id',
            field=models.CharField(default='pro', max_length=3),
            preserve_default=False,
        ),
    ]
